### ISSUE TITLE
Incompatibility with Diversity 1.1.0 and above and Charm in Minecraft 1.21 causing a crash

### ISSUE THREAD

**Issue by onthebobtrary** [FaeWulf/Diversity#4]
The game crashes in versions newer than Diversity 1.0.0 with Charm enabled. Here's the crash log:

`Prism Launcher version: 8.4 (official)

Launched instance in online mode

login.microsoftonline.com resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****, ****:****:****:****:****:****:****:****]

session.minecraft.net resolves to:
    [**.**.**.**, ****:****:****:****:****:****:****:****]

textures.minecraft.net resolves to:
    [**.**.**.**, ****:****:****:****:****:****:****:****]

api.mojang.com resolves to:
    [**.**.**.**, ****:****:****:****:****:****:****:****]

Minecraft folder is:
/Users/********/Library/Application Support/PrismLauncher/instances/test/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home/bin/java

Java is version 21.0.3, using 64 (aarch64) architecture, from Azul Systems, Inc..

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Users/********/Library/Application Support/PrismLauncher/instances/test/natives

Traits:
traits feature:is_quick_play_multiplayer
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-macos-arm64/3.3.3/lwjgl-freetype-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-macos-arm64/3.3.3/lwjgl-glfw-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-macos-arm64/3.3.3/lwjgl-jemalloc-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-macos-arm64/3.3.3/lwjgl-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-macos-arm64/3.3.3/lwjgl-openal-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-macos-arm64/3.3.3/lwjgl-opengl-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-macos-arm64/3.3.3/lwjgl-stb-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-macos-arm64/3.3.3/lwjgl-tinyfd-natives-macos-arm64-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/fabricmc/intermediary/1.21/intermediary-1.21.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.3 mixin.0.8.5/sponge-mixin-0.13.3 mixin.0.8.5.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.15.11/fabric-loader-0.15.11.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/minecraft/1.21/minecraft-1.21-client.jar

Native libraries:

Mods:
  [✔] charm-fabric-1.21-7.0.28
  [✔] diversity-1.2.0 1.21_fabric
  [✔] fabric-api-0.100.4 1.21

Params:
  --username  --version 1.21 --gameDir /Users/********/Library/Application Support/PrismLauncher/instances/test/.minecraft --assetsDir /Users/********/Library/Application Support/PrismLauncher/assets --assetIndex 17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="Prism Launcher: test", -XstartOnFirstThread, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 72190

unknown invokedynamic bsm: java/lang/runtime/SwitchBootstraps/typeSwitch(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/runtime/SwitchBootstraps/typeSwitch(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
[09:02:04] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[09:02:04] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[09:02:04] [main/INFO]: Loading 61 mods:
	- charm 7.0.28
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- diversity 1.2.0 1.21
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- midnightlib 1.5.7
	   |-- org_javassist_javassist 3.28.0-GA
	   \-- org_reflections_reflections 0.10.2
	- fabric-api 0.100.4 1.21
	   |-- fabric-api-base 0.4.42 6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67 b5597344d1
	   |-- fabric-biome-api-v1 13.0.28 6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22 0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10 6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52 0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15 6573ed8cd1
	   |-- fabric-command-api-v1 1.2.48 f71b366fd1
	   |-- fabric-command-api-v2 2.2.27 6a6dfa19d1
	   |-- fabric-commands-v0 0.2.65 df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14 b5597344d1
	   |-- fabric-convention-tags-v1 2.0.15 7f945d5bd1
	   |-- fabric-convention-tags-v2 2.3.2 78017270d1
	   |-- fabric-crash-report-info-v1 0.2.29 0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24 6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.9 16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0 6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12 6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10 e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.52 6573ed8cd1
	   |-- fabric-item-api-v1 11.0.0 afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2 78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47 0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45 df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11 8f3583aed1
	   |-- fabric-loot-api-v2 3.0.11 6573ed8cd1
	   |-- fabric-message-api-v1 6.0.13 6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0 fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0 ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12 d1321076d1
	   |-- fabric-particles-v1 4.0.2 6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10 65089712d1
	   |-- fabric-registry-sync-v0 5.0.23 78017270d1
	   |-- fabric-renderer-api-v1 3.3.0 0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5 48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67 df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48 73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6 b5597344d1
	   |-- fabric-rendering-v0 1.1.70 df3654b3d1
	   |-- fabric-rendering-v1 5.0.4 5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1 d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5 78017270d1
	   |-- fabric-screen-api-v1 2.0.24 b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.80 b5597344d1
	   |-- fabric-sound-api-v1 1.0.23 6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15 3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12 6573ed8cd1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.21
[09:02:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/********/Library/Application Support/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.3 mixin.0.8.5/sponge-mixin-0.13.3 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:02:04] [main/INFO]: Compatibility level set to JAVA_21
[09:02:04] [main/INFO]: Adding debug check: svenhjol.charm.mixin.MixinConfig$$Lambda/0x000000700123af88@5b7f9eaa
[09:02:04] [main/INFO]: Adding mixin disable check: svenhjol.charm.mixin.MixinConfig$$Lambda/0x000000700123b3b0@3c73d613
[09:02:04] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[09:02:05] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 206 milliseconds
[09:02:06] [main/WARN]: @Final field field_36535:Ljava/util/List; in diversity.mixins.json:enchantTableAcceptFurtherBookshelf.EnchantingTableBlockMixin from mod diversity should be final
[09:02:08] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[09:02:08] [Render thread/INFO]: Setting user: bobaonline
[09:02:08] [Render thread/INFO]: Loading 72 classes for charm
[09:02:08] [Render thread/ERROR]: No data fixer registered for charm:coral_squid
[09:02:09] [Render thread/ERROR]: No data fixer registered for charm:moobloom
[09:02:09] [Render thread/ERROR]: No data fixer registered for charm:chair
[09:02:09] [Render thread/ERROR]: No data fixer registered for charm:endermite_powder
[09:02:09] [Render thread/INFO]: Loading...
[09:02:09] [Render thread/INFO]: Register commands...
[09:02:09] [Render thread/INFO]: Register events...
[09:02:09] [Render thread/INFO]: Done!
[09:02:09] [Render thread/INFO]: Loading 37 classes for charm
[09:02:09] [Render thread/WARN]: @Redirect conflict. Skipping diversity.client.mixins.json:noLevelLimitAnvil.AnvilMixin from mod diversity->@Redirect::drawForeGroundRedirect(Lnet/minecraft/class_1656;)Z with priority 1000, already redirected by charm.mixins.json:feature.repair_cost_unlimited.AnvilScreenMixin from mod charm->@Redirect::hookRenderLabelsCheckAbilities(Lnet/minecraft/class_1656;Lnet/minecraft/class_332;II)Z with priority 1000
[09:02:09] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2024-07-01 09:02:09
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'charm'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.minecraft.client.gui.screen.ingame.HandledScreens.<clinit>(HandledScreens.java:87)
	at svenhjol.charm.charmony.client.ClientRegistry.lambda$menuScreen$9(ClientRegistry.java:154)
	at svenhjol.charm.charmony.Loader.deferred(Loader.java:123)
	at svenhjol.charm.charmony.Loader.setup(Loader.java:63)
	at svenhjol.charm.fabric.ClientInitializer.initCharm(ClientInitializer.java:20)
	at svenhjol.charm.fabric.ClientInitializer.onInitializeClient(ClientInitializer.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector drawForeGroundRedirect(Lnet/minecraft/class_1656;)Z in diversity.client.mixins.json:noLevelLimitAnvil.AnvilMixin from mod diversity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap client-diversity-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Mac OS X (aarch64) version 14.5
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 399685344 bytes (381 MiB) / 721420288 bytes (688 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm   Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 20480.00
	Virtual memory used (MiB): 16690.22
	Swap memory total (MiB): 12288.00
	Swap memory used (MiB): 10787.69
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 19989.02, total: 233752.44
	Space in storage for workdir (MiB): available: 19989.02, total: 233752.44
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		charm: Charm 7.0.28
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		diversity: Diversity 1.2.0 1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			midnightlib: MidnightLib 1.5.7
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		fabric-api: Fabric API 0.100.4 1.21
			fabric-api-base: Fabric API Base 0.4.42 6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67 b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28 6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22 0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10 6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52 0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15 6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48 f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27 6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65 df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14 b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15 7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2 78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29 0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24 6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9 16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0 6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12 6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10 e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52 6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0 afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2 78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47 0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45 df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11 8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11 6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13 6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0 fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0 ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12 d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2 6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10 65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23 78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0 0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5 48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67 df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48 73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6 b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70 df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4 5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1 d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5 78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24 b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80 b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23 6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15 3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12 6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
	Launched Version: 1.21
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /Users/********/Library/Application Support/PrismLauncher/instances/test/.minecraft/crash-reports/crash-2024-07-01_09.02.09-client.txt
Process exited with code 255.
Clipboard copy at: 01 Jul 2024 09:02:16  0800
Clipboard copy at: 01 Jul 2024 09:03:19  0800
Log upload triggered at: 01 Jul 2024 09:04:35  0800`

If version 1.0.0 of Diversity is used instead, [the game is able to start normally](https://mclo.gs/HoEsPR0).

**Comment by FaeWulf** [comment]
Thank you for reporting this issue! I will push the update asap.

**Comment by FaeWulf** [comment]
Updated https://modrinth.com/mod/faewufs-diversity/version/1.2.1+1.21

**Comment by onthebobtrary** [comment]
Thanks for the timely fix!
